[mypy]
ignore_missing_imports = True
explicit_package_bases = True

[mypy-services.fact_broker.sources.*]
ignore_errors = True

[mypy-agents.*]
ignore_errors = True

[mypy-services.compliance_doc.*]
ignore_errors = True

[mypy-services.carbon_lca.*]
ignore_errors = True

[mypy-main]
ignore_errors = True

[mypy-tests.*]
ignore_errors = True

[mypy-libs.shared.tasks]
ignore_errors = True

[mypy-libs.shared.eval.evaluator]
ignore_errors = True
